version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/dev.Dockerfile
    ports:
      - 80:8000
      - 443:443
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always
