version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/prod.Dockerfile
    ports:
      - 80:8000
      - 443:443
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always
